BTN_ATTACK_PATH := A_ScriptDir "\img\btn\attack.png"
BTN_ATTACK_WIDTH := 64
BTN_ATTACK_HEIGHT := 19
BTN_ARTILLERY_PATH := A_ScriptDir "\img\btn\Artillery.png"
BTN_ARTILLERY_WIDTH := 22
BTN_ARTILLERY_HEIGHT := 24
BTN_FAST_PATH := A_ScriptDir "\img\btn\Fast.png"
BTN_FAST_WIDTH := 23
BTN_FAST_HEIGHT := 22
BTN_HEAVY_PATH := A_ScriptDir "\img\btn\Heavy.png"
BTN_HEAVY_WIDTH := 21
BTN_HEAVY_HEIGHT := 17
BTN_LIGHT_PATH := A_ScriptDir "\img\btn\LIGHT.png"
BTN_LIGHT_WIDTH := 23
BTN_LIGHT_HEIGHT := 21
BTN_RANGED_PATH := A_ScriptDir "\img\btn\Ranged.png"
BTN_RANGED_WIDTH := 22
BTN_RANGED_HEIGHT := 24
BTN_ARTILLERY_PROGRESSIVE_PATH := A_ScriptDir "\img\btn\artillery_progressive.png"
BTN_ARTILLERY_PROGRESSIVE_WIDTH := 42
BTN_ARTILLERY_PROGRESSIVE_HEIGHT := 28
BTN_AUTO_BATTLE_PATH := A_ScriptDir "\img\btn\auto_battle.png"
BTN_AUTO_BATTLE_WIDTH := 60
BTN_AUTO_BATTLE_HEIGHT := 10
BTN_AUTO_BATTLE2_PATH := A_ScriptDir "\img\btn\auto_battle2.png"
BTN_AUTO_BATTLE2_WIDTH := 60
BTN_AUTO_BATTLE2_HEIGHT := 15
BTN_GREEN_OK_PATH := A_ScriptDir "\img\btn\greenOK.png"
BTN_GREEN_OK_WIDTH := 137
BTN_GREEN_OK_HEIGHT := 12
BTN_BROWN_OK_PATH := A_ScriptDir "\img\btn\brownOK.png"
BTN_BROWN_OK_WIDTH := 95
BTN_BROWN_OK_HEIGHT := 13
BTN_PAY_GOODS_PATH := A_ScriptDir "\img\btn\payGoods.png"
BTN_PAY_GOODS_WIDTH := 29
BTN_PAY_GOODS_HEIGHT := 31
IMG_UNBIRTHDAY_PATH := A_ScriptDir "\img\unbirthday.png"
IMG_UNBIRTHDAY_WIDTH := 215
IMG_UNBIRTHDAY_HEIGHT := 29
BTN_ABORT_QUEST_PATH := A_ScriptDir "\img\btn\abort.png"
BTN_ABORT_QUEST_WIDTH := 110
BTN_ABORT_QUEST_HEIGHT := 16
BTN_COLLECT_PATH := A_ScriptDir "\img\btn\collect.png"
BTN_COLLECT_WIDTH := 90
BTN_COLLECT_HEIGHT := 17
BTN_GE_ATTACK := A_ScriptDir "\img\btn\ge_attack.png"
BTN_GE_ATTACK_WIDTH := 103
BTN_GE_ATTACK_HEIGHT := 24
BTN_ARENA_BUTTON_PATH := A_ScriptDir "\img\btn\arena_button.png"
BTN_ARENA_BUTTON_WIDTH := 40
BTN_ARENA_BUTTON_HEIGHT := 33
BTN_ARENA_BUTTON_ALL_PATH := A_ScriptDir "\img\btn\arena_button_all.png"
BTN_ARENA_BUTTON_ALL_WIDTH := 63
BTN_ARENA_BUTTON_ALL_HEIGHT := 189
BTN_TAVERN_SEAT_PATH := A_ScriptDir "\img\btn\tavern_seat.png"
BTN_TAVERN_SEAT_WIDTH := 24
BTN_TAVERN_SEAT_HEIGHT := 17
BTN_FRONT_OF_FRIENDS_PATH := A_ScriptDir "\img\btn\front_of_friends.png"
BTN_FRONT_OF_FRIENDS_WIDTH := 15
BTN_FRONT_OF_FRIENDS_HEIGHT := 12
BTN_NEXT_FRIEND_PAGE_PATH := A_ScriptDir "\img\btn\next_friend_page.png"
BTN_NEXT_FRIEND_PAGE_WIDTH := 16
BTN_NEXT_FRIEND_PAGE_HEIGHT := 13
BTN_EXPAND_FRIENDS_PATH := A_ScriptDir "\img\btn\expand_friends.png"
BTN_EXPAND_FRIENDS_WIDTH := 14
BTN_EXPAND_FRIENDS_HEIGHT := 13
BTN_NEWS_PATH := A_ScriptDir "\img\btn\news.png"
BTN_NEWS_WIDTH := 171
BTN_NEWS_HEIGHT := 16
BTN_EVENT_HISTORY_PATH := A_ScriptDir "\img\btn\event_history.png"
BTN_EVENT_HISTORY_WIDTH := 143
BTN_EVENT_HISTORY_HEIGHT := 13
BTN_NEXT_EVENT_PAGE_PATH := A_ScriptDir "\img\btn\next_event_page.png"
BTN_NEXT_EVENT_PAGE_WIDTH := 13
BTN_NEXT_EVENT_PAGE_HEIGHT := 12
BTN_EXIT_PATH := A_ScriptDir "\img\btn\exit.png"
BTN_EXIT_WIDTH := 18
BTN_EXIT_HEIGHT := 13
BTN_COLLAPSE_FRIENDS_PATH := A_ScriptDir "\img\btn\close_friends.png"
BTN_COLLAPSE_FRIENDS_WIDTH := 17
BTN_COLLAPSE_FRIENDS_HEIGHT := 13
TOWN_HALL_PATH := A_ScriptDir "\img\town_hall.png"
FRIEND_ICON_PATH := A_ScriptDir "\img\friend_icon.png"
BTN_ALL_AGE_UNITS_PATH := A_ScriptDir "\img\btn\all_age_units.png"
BTN_EMPTY_TROOPS_PATH := A_ScriptDir "\img\empty_troops.png"
BTN_ARMY_MANAGEMENT_PATH := A_ScriptDir "\img\army_management.png"
BTN_DEFEND_PATH := A_ScriptDir "\img\btn\defend.png"
BTN_DEFEND_WIDTH := 113
BTN_DEFEND_HEIGHT := 26
QUEST_FNORD_PATH := A_ScriptDir "\img\quests\Fnord.png"
QUEST_PRINT_FULL_DAY_MEAL_PATH := A_ScriptDir "\img\quests\printFullDayMeals.png"
QUEST_PRODUCE_ANTI_GRAV_CARRIERS_PATH := A_ScriptDir "\img\quests\produceAntiGravCarriers.png"
QUEST_PRODUCE_HELIUM_PATH := A_ScriptDir "\img\quests\produceHelium.png"
QUEST_THE_SPINKS_PATH := A_ScriptDir "\img\quests\theSpink.png"
QUEST_UNBIRTHDAY_PATH := A_ScriptDir "\img\quests\Unbirthday.png"

